### ISSUE TITLE
conjure-up install keeps running even after install fails

### ISSUE THREAD

**Issue by babatundebusari** [ubuntu/conjure-up#13]
I noticed that after running `conjure-up openstack`, even after the installation fails and errors out, using htop the conjure-up openstack installation script/process is still running in the background.

**Comment by battlemidget** [comment]
Interesting UK take a look

**Comment by mikemccracken** [comment]
I haven't seen this in testing. @battlemidget have you been able to reproduce it?
This needs a milestone or needs to be closed.

**Comment by battlemidget** [comment]
Nope can't reproduce
