### ISSUE TITLE
Can't get the console of a LXD container.

### ISSUE THREAD

**Issue by rhickstedjr** [ubuntu/conjure-up#14]
Is it possible to get a console to a LCD container?

![screenshot from 2016-05-07 15-28-46](https://cloud.githubusercontent.com/assets/12604519/15094953/9a61ff04-1468-11e6-89da-6df1cd117395.png)

Regards,

**Comment by battlemidget** [comment]
Unfortunately that hasn't worked in awhile and I'm not sure why. I'll need to talk to the OpenStack charmers to figure out why

**Comment by babatundebusari** [comment]
@rhickstedjr can you please help me?
seems your installation is working

I have been having issues installing this thing and no luck for almost 3 months now

are you installing Openstack Autopilot or the LXD version?

**Comment by rhickstedjr** [comment]
LXD version I just saw a demo in Austin at the last summit.

Thanks,

Sent from my iPhone

On May 7, 2016, at 4:13 PM, babatundebusari <notifications@github.com<mailto:notifications@github.com>> wrote:


@rhickstedjr<https://github.com/rhickstedjr> can you please help me?
seems your installation is working

I have been having issues installing this thing and no luck for almost 3 months now

are you installing Openstack Autopilot or the LXD version?

-

**Comment by babatundebusari** [comment]
@rhickstedjr Did you ever try to install `Openstack Autopilot`
That one i think does not work

**Comment by rhickstedjr** [comment]
I have installed the ubuntu juju based openstack install on 12x Intel NUCs.  I have not really used autopilot.


Thanks,

Rick

________________________________

**Comment by babatundebusari** [comment]
@rhickstedjr how? using conjure-up? or using the Ubuntu 14.04 LTS Openstack Autopilot using landscape?

If you can help me take a look what am doing wrong will highly appreciate it man
I have been trying this thing for 3 months, i have reinstalled OS like so many times, its crazy
Also installing OS takes over 30 minutes, i mean not sure am if its me or just takes that long. Even my hard drives are wearing out with the writes every time

Can't seem to get this thing to work and not sure what is wrong and where

**Comment by babatundebusari** [comment]
How do i access the dashboard for the LXD version?

I started installation but because my VPN connection to the datacenter keeps reconnecting, i might have lost the realtime SSH session for the installation so am stuck on this screen after like an hour or more now 

<img width="1836" alt="screen shot 2016-05-07 at 8 52 42 pm" src="https://cloud.githubusercontent.com/assets/6054104/15095473/e1ba4f78-1495-11e6-8e7d-7d98c032c27c.png">


So i think the installation probably finished, because from `htop` the machine is pretty busy and its over an hour since installation started.

<img width="1848" alt="screen shot 2016-05-07 at 8 52 14 pm" src="https://cloud.githubusercontent.com/assets/6054104/15095482/3a83aac8-1496-11e6-8e28-fefc91c2031a.png">

So how do i know if it really has completed? and how do i access the dashboard GUI?

**Comment by battlemidget** [comment]
So you can re-run `conjure-up openstack -s` with the (-s) and it'll reconnect to your deployment. If you want to access your dashboard from a remote system do something like:

```
sshuttle -r user@host 10.26.91.0/24
```

Then you should be able to connect directly to the dashboard's ip address 10.26.91.139 using admin/openstack to login

**Comment by battlemidget** [comment]
Also be aware of https://bugs.launchpad.net/juju-core/+bug/1574844 which is a problem with juju and ipv6 which you seem to be hitting as well. It can easily be fixed by disabling ipv6

see https://askubuntu.com/questions/440649/how-to-disable-ipv6-in-ubuntu-14-04

**Comment by rhickstedjr** [comment]
When it is done you will see the Horizon access URL at the bottom of the conjure-up screen.


Thanks,

Rick



________________________________

**Comment by babatundebusari** [comment]
Looks like the reconnects automatically itself, so apparently it takes REALLY long to complete installation

Still progressing as i can see

<img width="1838" alt="screen shot 2016-05-07 at 9 13 48 pm" src="https://cloud.githubusercontent.com/assets/6054104/15095540/bab7293e-1498-11e6-9470-a1e7029f16d2.png">

**Comment by babatundebusari** [comment]
here is where am at now, don't know if this will fail again after probably over 2 hours now

<img width="1843" alt="screen shot 2016-05-07 at 9 23 28 pm" src="https://cloud.githubusercontent.com/assets/6054104/15095556/0d8c0958-149a-11e6-8165-997888e9d9ec.png">

**Comment by battlemidget** [comment]
Yea neutron-api has a ipv6 address which causing it to be in error, you'll want to reference that bug i posted earlier

**Comment by babatundebusari** [comment]
<img width="1849" alt="screen shot 2016-05-07 at 9 27 41 pm" src="https://cloud.githubusercontent.com/assets/6054104/15095565/9c7348b6-149a-11e6-917b-0c384970b5c8.png">

**Comment by babatundebusari** [comment]
@battlemidget 
so i should disable ipv6 right now as the installation is currently running?

Also to disable ipv6, i need to do this?

```
up vote
96
down vote
accepted
To disable ipv6, you have to open /etc/sysctl.conf using any text editor and insert the following lines at the end:

net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
If ipv6 is still not disabled, then the problem is that sysctl.conf is still not activated.

To solve this, open a terminal(Ctrl+Alt+T) and type the command,

sudo sysctl -p
You will see this in the terminal:

net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
After that, if you run:

$ cat /proc/sys/net/ipv6/conf/all/disable_ipv6
It will report:

1
If you see 1, ipv6 has been successfully disabled.
```

**Comment by babatundebusari** [comment]
@battlemidget if i disable ipv6 now the installation is still running, won't that break installation?
or i have to rerun the installation all over again from scratch?

**Comment by babatundebusari** [comment]
ok since no quick reply i have gone ahead and disabled ipv6

<img width="567" alt="screen shot 2016-05-07 at 9 45 09 pm" src="https://cloud.githubusercontent.com/assets/6054104/15095606/168b7716-149d-11e6-9117-88e56f087a04.png">


and now the installation still hows ipv6 though not sure if things will complete now

<img width="1823" alt="screen shot 2016-05-07 at 9 46 29 pm" src="https://cloud.githubusercontent.com/assets/6054104/15095611/308c0e32-149d-11e6-82a0-d52d09782a6a.png">

**Comment by babatundebusari** [comment]
@battlemidget 

Ok i have disabled ipv6, what do i do next to make this installation complete successfully?

**Comment by rhickstedjr** [comment]
I disabled IPv6 to get mine installed as well.

Thanks,

Sent from my iPhone

On May 7, 2016, at 6:53 PM, babatundebusari <notifications@github.com<mailto:notifications@github.com>> wrote:


@battlemidget<https://github.com/battlemidget>

Ok i have disabled ipv6, what do i do next to make this installation complete successfully?

-

**Comment by babatundebusari** [comment]
@rhickstedjr 
one quick question
when you choose the ip block to be used by LXD, what ip block did you choose?

do you have to have a vlan dedicated for LXD?

Am asking because LXD choose to use 10.26.91.0/24 and now it says i can access dashboard on http://10.26.91.139/horizon but i have no network connection to get to that network.

I can get to the VLAN  i created and that VLAN can get to that network , but i can't go directly to that network.

So wanted to know how to choose the network to be used by LXD

**Comment by babatundebusari** [comment]
never mind
just figured i have to choose an IP block in my VLAN for lxd

**Comment by moula** [comment]
Bonjour, 
Juste to say that i try to deploy it, if someone has a howto , I'm interested. especially for the physical architecture multi servers. conjure-up will plaise me.
Merci.

**Comment by babatundebusari** [comment]
ok just tried another brand new install of Ubuntu 16.04 LTS on a different server
and getting errors
I also made sure no ipv6 for this install this time

screesnhots posted below

![lxd1](https://cloud.githubusercontent.com/assets/6054104/15096853/99843132-14d7-11e6-9937-962ba928c272.PNG)
![lxd2](https://cloud.githubusercontent.com/assets/6054104/15096852/99831306-14d7-11e6-85da-0e9cfff56725.PNG)
![lxd3](https://cloud.githubusercontent.com/assets/6054104/15096854/99845d2e-14d7-11e6-86d0-448ce31c43c9.PNG)
![lxd4](https://cloud.githubusercontent.com/assets/6054104/15096855/9986546c-14d7-11e6-8505-289650205b7f.PNG)

**Comment by battlemidget** [comment]
So there is an update waiting to be pushed to the archive that fixes this error, for now though you can add our ppa, 

```
apt-add-repository ppa:conjure/ppa
```

Soon as it gets approved it'll be in the archive, you don't need to re-install everything though just running

```
conjure-up openstack -s
```

Will bring you back to the status screen and kick off the post processing to make sure your services are configured. Then you can access the dashboard (via sshuttle as posted earlier)

**Comment by babatundebusari** [comment]
@battlemidget 

ok i did that

```
ubuntu@ubuntu101:~$ sudo apt-add-repository ppa:conjure/ppa
[sudo] password for ubuntu:
 Contains the conjure runtime and applicable packages supported by conjure
 More info: https://launchpad.net/~conjure/+archive/ubuntu/ppa
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keyring `/tmp/tmpnnivzn1i/secring.gpg' created
gpg: keyring `/tmp/tmpnnivzn1i/pubring.gpg' created
gpg: requesting key 4CD5D8B2 from hkp server keyserver.ubuntu.com
gpg: /tmp/tmpnnivzn1i/trustdb.gpg: trustdb created
gpg: key 4CD5D8B2: public key "Launchpad PPA for conjure" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
ubuntu@ubuntu101:~$ conjure-up openstack -s
```
<img width="1823" alt="screen shot 2016-05-08 at 11 19 12 am" src="https://cloud.githubusercontent.com/assets/6054104/15098600/bcde4032-150e-11e6-90f8-8bdcc0044a79.png">


and here is what i get after

<img width="1178" alt="screen shot 2016-05-08 at 11 18 14 am" src="https://cloud.githubusercontent.com/assets/6054104/15098601/c207a3a0-150e-11e6-857a-05e60f21a9d7.png">

**Comment by babatundebusari** [comment]
ok i am having problem connecting to the ip address block created by LXD
LXD creates this IP address block so how does one route to that network block?

the machine where LXD is setup has access to the block

```
ubuntu@ubuntu101:~$ ping 10.247.10.1
PING 10.247.10.1 (10.247.10.1) 56(84) bytes of data.
64 bytes from 10.247.10.1: icmp_seq=1 ttl=64 time=0.049 ms
64 bytes from 10.247.10.1: icmp_seq=2 ttl=64 time=0.055 ms
64 bytes from 10.247.10.1: icmp_seq=3 ttl=64 time=0.068 ms
64 bytes from 10.247.10.1: icmp_seq=4 ttl=64 time=0.059 ms
64 bytes from 10.247.10.1: icmp_seq=5 ttl=64 time=0.053 ms
64 bytes from 10.247.10.1: icmp_seq=6 ttl=64 time=0.064 ms
^C
--- 10.247.10.1 ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 5001ms
rtt min/avg/max/mdev = 0.049/0.058/0.068/0.006 ms
ubuntu@ubuntu101:~$ ping 10.247.10.228
PING 10.247.10.228 (10.247.10.228) 56(84) bytes of data.
64 bytes from 10.247.10.228: icmp_seq=1 ttl=64 time=0.065 ms
64 bytes from 10.247.10.228: icmp_seq=2 ttl=64 time=0.068 ms
64 bytes from 10.247.10.228: icmp_seq=3 ttl=64 time=0.076 ms
64 bytes from 10.247.10.228: icmp_seq=4 ttl=64 time=0.067 ms
64 bytes from 10.247.10.228: icmp_seq=5 ttl=64 time=0.073 ms
64 bytes from 10.247.10.228: icmp_seq=6 ttl=64 time=0.060 ms
^C
--- 10.247.10.228 ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 5006ms
rtt min/avg/max/mdev = 0.060/0.068/0.076/0.007 ms
```

but another machine with another IP address on VLAN cannot get to it

```
ubuntu@ubuntu102:~$ ping 10.247.10.1
PING 10.247.10.1 (10.247.10.1) 56(84) bytes of data.
64 bytes from 10.247.10.1: icmp_seq=1 ttl=64 time=0.430 ms
64 bytes from 10.247.10.1: icmp_seq=2 ttl=64 time=0.219 ms
64 bytes from 10.247.10.1: icmp_seq=3 ttl=64 time=0.235 ms
64 bytes from 10.247.10.1: icmp_seq=4 ttl=64 time=0.226 ms
64 bytes from 10.247.10.1: icmp_seq=5 ttl=64 time=0.292 ms
64 bytes from 10.247.10.1: icmp_seq=6 ttl=64 time=0.206 ms
^C
--- 10.247.10.1 ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 4997ms
rtt min/avg/max/mdev = 0.206/0.268/0.430/0.077 ms
ubuntu@ubuntu102:~$ ping 10.247.10.228
PING 10.247.10.228 (10.247.10.228) 56(84) bytes of data.
From 10.247.0.102 icmp_seq=1 Destination Host Unreachable
From 10.247.0.102 icmp_seq=2 Destination Host Unreachable
From 10.247.0.102 icmp_seq=3 Destination Host Unreachable
From 10.247.0.102 icmp_seq=4 Destination Host Unreachable
From 10.247.0.102 icmp_seq=5 Destination Host Unreachable
From 10.247.0.102 icmp_seq=6 Destination Host Unreachable
^C
--- 10.247.10.228 ping statistics ---
8 packets transmitted, 0 received, +6 errors, 100% packet loss, time 7039ms
pipe 3
```

What do i do now? and how do i select ip address block of LXD so that i can still route to the ip network?

**Comment by rinchen** [comment]
@rhickstedjr  I think the post above this comment was meant to highlight you and not me. :-)

**Comment by rhickstedjr** [comment]
The solution for this was on the issue 8 thread:

# hit enter without typing any passwords in
$ ssh-keygen 
$ source /usr/share/openstack/bundles/common-openstack/novarc
$ openstack keypair create —public-key $HOME/.ssh/id_rsa.pub ubuntu-keypair

Thanks,

Rick

**Comment by babatundebusari** [comment]
@rhickstedjr 

Did you see my last response about not able to access the IP of dashboard?

How did you setup your networking?
You can read my last comment above

**Comment by rhickstedjr** [comment]
I took the defaults configuring the LXD bridge.

Note:  you can’t access the horizon UI until the deployment is complete with the message I sent you.

Thanks,

Rick

**Comment by babatundebusari** [comment]
@rhickstedjr 

Ok will apply the fix you sent, but to be honest i generated SSH keys earlier before and since then never got any error messages anymore, as you see from my latest screenshots, everything seem to be fine now only need to access the dashboard

Also do you mind giving an example of how your networking for LXD is? What is your VLAN like and what was the ip address block like?

From the networking i think i may have issues accessing is still just from what i posted earlier, i couldn't ping that ip address from another machine

**Comment by babatundebusari** [comment]
@battlemidget 

I sent you the login to this machine to your email

Thanks

**Comment by battlemidget** [comment]
As I posted at least twice already, you need to use sshuttle to be able to access the dashboard from a remote machine

**Comment by babatundebusari** [comment]
@battlemidget 

Where did you mention sshuttle?

I am already using a VPN, or how do you think i connect to those machines on their private IP addresses? I only give you the public IP address because its easier than setting you up with VPN to get in

Were you able to login to see the machine?
Am i missing anything?

Please look at the previous message i wrote above
will paste it below again

#####
@battlemidget 
@rhickstedjr 
ok i am having problem connecting to the ip address block created by LXD
LXD creates this IP address block so how does one route to that network block?

ip address of horizon dashboard is `10.247.10.288`
VLAN is `10.247.0.0/16`
LXD ip network block is `10.247.10.0/24`

the machine where LXD is setup has access to the block

```
ubuntu@ubuntu101:~$ ifconfig
enp4s0f0  Link encap:Ethernet  HWaddr 78:e7:d1:21:e9:e8
          inet addr:10.247.0.101  Bcast:10.247.255.255  Mask:255.255.0.0
          inet6 addr: fe80::7ae7:d1ff:fe21:e9e8/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:3271187 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2389657 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:2999060691 (2.9 GB)  TX bytes:354598731 (354.5 MB)
          Memory:ef000000-ef01ffff
ubuntu@ubuntu101:~$ ping 10.247.10.1
PING 10.247.10.1 (10.247.10.1) 56(84) bytes of data.
64 bytes from 10.247.10.1: icmp_seq=1 ttl=64 time=0.049 ms
64 bytes from 10.247.10.1: icmp_seq=2 ttl=64 time=0.055 ms
64 bytes from 10.247.10.1: icmp_seq=3 ttl=64 time=0.068 ms
64 bytes from 10.247.10.1: icmp_seq=4 ttl=64 time=0.059 ms
64 bytes from 10.247.10.1: icmp_seq=5 ttl=64 time=0.053 ms
64 bytes from 10.247.10.1: icmp_seq=6 ttl=64 time=0.064 ms
^C
--- 10.247.10.1 ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 5001ms
rtt min/avg/max/mdev = 0.049/0.058/0.068/0.006 ms
ubuntu@ubuntu101:~$ ping 10.247.10.228
PING 10.247.10.228 (10.247.10.228) 56(84) bytes of data.
64 bytes from 10.247.10.228: icmp_seq=1 ttl=64 time=0.065 ms
64 bytes from 10.247.10.228: icmp_seq=2 ttl=64 time=0.068 ms
64 bytes from 10.247.10.228: icmp_seq=3 ttl=64 time=0.076 ms
64 bytes from 10.247.10.228: icmp_seq=4 ttl=64 time=0.067 ms
64 bytes from 10.247.10.228: icmp_seq=5 ttl=64 time=0.073 ms
64 bytes from 10.247.10.228: icmp_seq=6 ttl=64 time=0.060 ms
^C
--- 10.247.10.228 ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 5006ms
rtt min/avg/max/mdev = 0.060/0.068/0.076/0.007 ms
```

but another machine with another IP address on VLAN cannot get to it

```
ubuntu@ubuntu102:~$ ifconfig
enp4s0f0  Link encap:Ethernet  HWaddr 78:e7:d1:21:e7:e8
          inet addr:10.247.0.102  Bcast:10.247.255.255  Mask:255.255.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:3659723 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2166837 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:3001811726 (3.0 GB)  TX bytes:394821470 (394.8 MB)
          Memory:ef000000-ef01ffff
ubuntu@ubuntu102:~$ ping 10.247.10.1
PING 10.247.10.1 (10.247.10.1) 56(84) bytes of data.
64 bytes from 10.247.10.1: icmp_seq=1 ttl=64 time=0.430 ms
64 bytes from 10.247.10.1: icmp_seq=2 ttl=64 time=0.219 ms
64 bytes from 10.247.10.1: icmp_seq=3 ttl=64 time=0.235 ms
64 bytes from 10.247.10.1: icmp_seq=4 ttl=64 time=0.226 ms
64 bytes from 10.247.10.1: icmp_seq=5 ttl=64 time=0.292 ms
64 bytes from 10.247.10.1: icmp_seq=6 ttl=64 time=0.206 ms
^C
--- 10.247.10.1 ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 4997ms
rtt min/avg/max/mdev = 0.206/0.268/0.430/0.077 ms
ubuntu@ubuntu102:~$ ping 10.247.10.228
PING 10.247.10.228 (10.247.10.228) 56(84) bytes of data.
From 10.247.0.102 icmp_seq=1 Destination Host Unreachable
From 10.247.0.102 icmp_seq=2 Destination Host Unreachable
From 10.247.0.102 icmp_seq=3 Destination Host Unreachable
From 10.247.0.102 icmp_seq=4 Destination Host Unreachable
From 10.247.0.102 icmp_seq=5 Destination Host Unreachable
From 10.247.0.102 icmp_seq=6 Destination Host Unreachable
^C
--- 10.247.10.228 ping statistics ---
8 packets transmitted, 0 received, +6 errors, 100% packet loss, time 7039ms
pipe 3
```

What do i do now? and how do i select ip address block of LXD so that i can still route to the ip network? 
#####

**Comment by battlemidget** [comment]
Use sshuttle as I said before:

https://github.com/Ubuntu-Solutions-Engineering/conjure-up/issues/14#issuecomment-217681478

**Comment by babatundebusari** [comment]
@battlemidget 
So where do i use sshuttle from?

From my computer or from a desktop in the VLAN?

From my computer i already use VPN to get into my remote infrastructure in a datacenter

So where exactly will sshuttle command be ran from?

**Comment by battlemidget** [comment]
In addition to using your VPN you would run this sshuttle command to access the LXD containers from your computer.

**Comment by battlemidget** [comment]
Ok so before this issue was hijacked I've create the necessary bugs to have Horizon support a Console via Nova LXD.

https://github.com/lxc/nova-lxd/issues/128

@rhickstedjr as it stands now there isn't a way to make this work and those bugs are for tracking that progress.

**Comment by battlemidget** [comment]
Closing this as it's being ttracked in the previous comments bug
