### ISSUE TITLE
new: bundle overview screen for showing bundle README before service walkthru

### ISSUE THREAD

**Issue by mikemccracken** [ubuntu/conjure-up#169]
just an info screen to learn about the bundle and what the upcoming services will combine to do.

A side benefit is that we give bootstrapping / add-model a little more time to run while the user reads so we don't wait as long to deploy and things seem faster later on

**Comment by battlemidget** [comment]
I think we can merge https://github.com/ubuntu/conjure-up/issues/205 in here as well
