### ISSUE TITLE
Possibility to provide (or propagate) proxy settings and bootstrap timeout

### ISSUE THREAD

**Issue by ptylenda** [ubuntu/conjure-up#171]
In previous versions of juju (prior to 2.0?) it was possible to change timeout and other settings like this: http://askubuntu.com/questions/458535/how-to-change-juju-bootstrap-time-from-the-10min-it-gives-you

In latest version of juju (2.0-beta9-xenial-amd64) and conjure-up (2.0.0.3-0~459~ubuntu16.04.1) I don't see any way to provide proxy settings and juju bootstrap timeout. There is a thread on stackoverflow which already mentions that: http://askubuntu.com/questions/770624/how-to-set-bootstrap-timeout-when-deploying-landscape-dense-maas-from-conjure-up

Currently I am workarounding this by adding in /usr/share/conjure-up/conjure/juju.py (L:120) additional hardcoded command line params: --config bootstrap-timeout=3600 --config http-proxy=[proxy] --config https-proxy=[proxy] --config apt-http-proxy=[proxy] --config apt-https-proxy=[proxy] --config --config apt-ftp-proxy=[proxy] --config ftp-proxy=[proxy] no-proxy=[IPs]

It would be good to have these parameters configurable or provide a possibility to propagate them from env variables/MAAS 2.0 settings (if MAAS is used).

**Comment by battlemidget** [comment]
Thanks I'll make sure this gets in the next prerelease

**Comment by ptylenda** [comment]
Thanks! :)

**Comment by battlemidget** [comment]
@ptylenda np, this will be in the PPA by next Tuesday July 5th.

**Comment by natejgardner** [comment]
I'm using this PPA, but I'm not seeing any global way to set the proxy before a model is created. It seems the only workaround is to use `--config` everywhere.

See my AskUbuntu post: http://askubuntu.com/q/852154/573381
