### ISSUE TITLE
No available machine matches constraints: zone=default

### ISSUE THREAD

**Issue by jleavers** [ubuntu/conjure-up#175]
Versions: 

* maas: 2.0.0~beta7
* juju: 2.0-beta9.1
* conjure-up: 2.0.0.3-0~459~ubuntu16.04.1

I have 7x machines available via maas - after running conjure-up openstack and "Deploy all 14 Remaining Applications with Bundle Defaults" I get an error on the screen and in the log:

```
conjure-up/openstack: [ERROR] Showing dialog for exception:#012Traceback (most recent call last):#012  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run#012    result = self.fn(*self.args, **self.kwargs)#012  File "/usr/share/conjure-up/conjure/controllers/deploystatus/common.py", line 38, in wait_for_applications#012    raise Exception(result['message'])#012Exception: Machine creation errors:#0123: cannot run instances: cannot run instance: No available machine matches constraints: zone=default
```

Looking at juju status I can see that 6x machines have been used:

```
UNIT                     WORKLOAD  AGENT       MACHINE  PORTS   PUBLIC-ADDRESS  MESSAGE
ceph-mon/0               active    idle        0                192.168.1.5     Unit is ready and clustered
ceph-mon/1               active    idle        1                192.168.1.3     Unit is ready and clustered
ceph-mon/2               active    idle        2                192.168.1.4     Unit is ready and clustered
ceph-osd/0               unknown   allocating  3                                Waiting for agent initialization to finish
ceph-osd/1               active    idle        4                192.168.1.6     Unit is ready (1 OSD)
ceph-osd/2               unknown   allocating  5                                Waiting for agent initialization to finish
ceph-radosgw/0           blocked   idle        6        80/tcp  192.168.1.7     Missing relations: mon, identity
glance/0                 unknown   allocating  7                                Waiting for agent initialization to finish
keystone/0               waiting   idle        8                192.168.1.8     Incomplete relations: database
mysql/0                  unknown   allocating  9                                Waiting for agent initialization to finish
neutron-api/0            unknown   allocating  10                               Waiting for agent initialization to finish
neutron-gateway/0        unknown   allocating  11                               Waiting for agent initialization to finish
nova-cloud-controller/0  unknown   allocating  12                               Waiting for agent initialization to finish
nova-compute/0           unknown   allocating  13                               Waiting for agent initialization to finish
openstack-dashboard/0    unknown   allocating  14                               Waiting for agent initialization to finish
rabbitmq-server/0        unknown   allocating  15                               Waiting for agent initialization to finish

MACHINE  STATE    DNS        INS-ID   SERIES   AZ
0        started  192.168.1.5 4y3h8m   xenial  default
1        started  192.168.1.3 4y3h8f   xenial  default
2        started  192.168.1.4 4y3h8h   xenial  default
3        error                pending  xenial
4        started  192.168.1.6 4y3h8n   xenial  default
5        error                pending  xenial
6        started  192.168.1.7 4y3h8p   xenial  default
7        error                pending  xenial
8        started  192.168.1.8 4y3h8q   xenial  default
9        error                pending  xenial
10       error                pending  xenial
11       error                pending  xenial
12       error                pending  xenial
13       error                pending  xenial
14       error                pending  xenial
15       error                pending  xenial
```

1. Is it expected that the install requires 16x physical servers? Or have I missed something that would allow me to use 3x servers, or 6x servers, with colocated jobs, similar to OpenStack Autopilot?
2. The first machine (192.168.1.2) has been bootstrapped but it isn't clear what it will be used for, can you advise?

Thanks.

**Comment by mikemccracken** [comment]
Hi, thanks for giving this a try. We are still in active development on the conjure-up spells for openstack, and appreciate the early feedback!

1. 'conjure-up openstack' will eventually include multiple "spells", which if you're familiar with juju are bundles with extra metadata and scripts. The spell that we currently have enabled is this bundle: https://api.jujucharms.com/charmstore/v5/~conjure/openstack-novalxd/archive/bundle.yaml 

you can see that it specifies units for each application but doesn't assign them to machines. So in this case, it is expected that it'll use a machine per unit when you deploy it to MAAS.

The way to fix this would be to tweak that bundle to include machines and a `to:` spec for each of the applications. If you want to try that out, you can fork it from here https://github.com/battlemidget/openstack-novalxd  and run conjure-up on it directly from github by `conjure-up mygithubusername/openstack-novalxd`. It will just pull the 'master' branch and use that bundle and scripts.

However, this may not work yet, we haven't had a chance to flesh out what we need to deploy bundles with machine constraints. If you want to try and file issues, we'd be glad to see them, or you can just follow https://github.com/ubuntu/conjure-up/issues/176 to see our progress.

2. I suspect that the .2 machine was used as the juju controller, created during bootstrap. If you're unfamiliar with juju 2.0, it has added the concept of multiple models per controller, and the bootstrap machine is created in a model called `controller`. So if you want to see the status of that machine, you will need to switch to the model named `controller` first, like this: `juju switch controller`, then `juju status` will show you that machine. `juju controllers` should show you one controller, with an arbitrary name, and `juju models` should show you two models, one named `controller` and another either named `default` or some arbitrary name. The one named `default` is where your services were deployed into, and its what you are seeing in `juju status`

**Comment by jleavers** [comment]
Thanks, I will try tweaking the bundle.

Re: the .2 machine - yes, the bootstrap machine was created in the controller model. Thanks. Is it required permanently? I'm just trying to split specs between things like maas/juju and compute.

**Comment by battlemidget** [comment]
Next release will support machine directives from bundles
