### ISSUE TITLE
'openstack' curated spell does not include a low-machine-count bundle

### ISSUE THREAD

**Issue by mikemccracken** [ubuntu/conjure-up#176]
The current spell 'openstack-novalxd' uses one machine per application unit. We need to add a squashed bundle and support adding machines and deploying onto them.

**Comment by battlemidget** [comment]
We need to conjure-up enable the openstack-base bundle, maybe we can do that there?

**Comment by battlemidget** [comment]
Tracking this work here, https://github.com/battlemidget/openstack-bundles/tree/patch-conjurfied

**Comment by battlemidget** [comment]
Here is our conjure-up enabled spell:

https://jujucharms.com/u/spells/openstack
