### ISSUE TITLE
Deployment without success. no issue to import key key ssh. 

### ISSUE THREAD

**Issue by moula** [ubuntu/conjure-up#178]
Jun 23 12:36:04 maas conjure-up/openstack: [ERROR] Showing dialog for exception:#012Traceback (most recent call last):#012  File "/usr/share/conjure-up/conjure/juju.py", line 385, in do_add_all#012    params=params)#012  File "/usr/share/conjure-up/macumba/v2.py", line 113, in _request#012    'Params': params})#012  File "/usr/share/conjure-up/macumba/v2.py", line 124, in call#012    return self.receive(req_id, timeout)#012  File "/usr/share/conjure-up/macumba/api.py", line 126, in receive#012    raise ServerError(res['Error'], res)#012macumba.errors.ServerError: (ServerError(...), 'application "neutron-openvswitch" not found')#012#012During handling of the above exception, another exception occurred:#012#012Traceback (most recent call last):#012  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run#012    result = self.fn(*self.args, **self.kwargs)#012  File "/usr/share/conjure-up/conjure/juju.py", line 36, in _decorator#012    return f(*args, **kwargs)#012  File "/usr/share/conjure-up/conjure/juju.py", line 388, in do_add_all#012    exc_cb(e)#012  File "/usr/share/conjure-up/conjure/controllers/deploy/gui.py", line 25, in __handle_exception#012    app.ui.show_exception_message(exc)#012  File "/usr/share/conjure-up/conjure/ui/__init__.py", line 17, in show_exception_message#012    self.frame.body = ErrorView(ex.args[0])#012  File "/usr/share/conjure-up/ubuntui/views/error.py", line 23, in __init__#012    Padding.center_80(Color.error_major(Text(error))),#012  File "/usr/lib/python3/dist-packages/urwid/widget.py", line 836, in __init__#012    self.set_text(markup)#012  File "/usr/lib/python3/dist-packages/urwid/widget.py", line 879, in set_text#012    self._text, self._attrib = decompose_tagmarkup(markup)#012  File "/usr/lib/python3/dist-packages/urwid/util.py", line 375, in decompose_tagmarkup#012    tl, al = _tagmarkup_recurse(tm, None)#012  File "/usr/lib/python3/dist-packages/urwid/util.py", line 416, in _tagmarkup_recurse#012    raise TagMarkupException("Invalid markup element: %r" % tm)#012urwid.util.TagMarkupException: Invalid markup element: ServerError(ServerError(...), 'application "neutron-openvswitch" not found')
Jun 23 12:36:05 maas conjure-up/openstack: [DEBUG] 00_deploy-done:13 - Running deploy-done for OpenStack installation.
Jun 23 12:36:31 maas conjure-up/openstack: [DEBUG] Importing trusty
Jun 23 12:36:33 maas conjure-up/openstack: [DEBUG] Importing xenial
Jun 23 12:36:53 maas conjure-up/openstack: [DEBUG] Adding ssh public key ~/.ssh/id_rsa.pub

**Comment by moula** [comment]
![capture du 2016-06-23 12-36-03](https://cloud.githubusercontent.com/assets/1804815/16300640/389d4cbc-3941-11e6-887a-3d88f94b1c4a.png)

**Comment by battlemidget** [comment]
Moved this to the actual spell as this isn't a problem within conjure-up core
