### ISSUE TITLE
pre-deploy fails intermittently for LXD provider after an add-model

### ISSUE THREAD

**Issue by battlemidget** [ubuntu/conjure-up#197]
LXD reports it can't edit its profile from a pre-deploy script if the juju environment is already bootstrapped. Meaning we just run juju add-model then handle our pre-deploy tasks. This doesn't happen on a fresh bootstrap.

We may just need to put a timeout in our pre-deploy scripts to wait for the profile to become editable.

**Comment by battlemidget** [comment]
Haven't reproduced yet, leaving open for now though

**Comment by mikemccracken** [comment]
I ran into this a few times just now, we seem to be attempting to update the profile before it exists. adding logging for the pre-deploy's stderr confirms this.

**Comment by mikemccracken** [comment]
This needs to be fixed in the pre-deploy script. I've pushed on example fix to a bundle here https://github.com/mikemccracken/bundle-wordpress/commit/5022d8761c3798c440f7cf1b387056d66cddcf17

**Comment by mikemccracken** [comment]
Closing because this should be fixed in the spells.
