### ISSUE TITLE
doesn't work again, with juju 2 beta11, MAAS 2 rc1...

### ISSUE THREAD

**Issue by moula** [ubuntu/conjure-up#201]
![machines_maas_maas_-_2016-07-02_11 17 27](https://cloud.githubusercontent.com/assets/1804815/16539658/44b88006-404a-11e6-8f93-ef73050d9404.png)

![machines_maas_maas_-_2016-07-02_11 28 09](https://cloud.githubusercontent.com/assets/1804815/16539661/61f4c38c-404a-11e6-9419-6e013fa0a3cb.png)

![capture du 2016-07-02 11-32-03](https://cloud.githubusercontent.com/assets/1804815/16539666/80ef370e-404a-11e6-8590-f54f92a71af8.png)

**Comment by moula** [comment]
admin@maas:/home/moula$ tail -f /var/log/conjure-up/openstack.log 
Jul  2 11:08:29 maas conjure-up/openstack: [DEBUG] app.py:86 - Beta release found, checking minimum requirements.
Jul  2 11:09:05 maas conjure-up/openstack: [DEBUG] gui.py:53 - Performing bootstrap: earl maas/10.1.1.100
Jul  2 11:09:05 maas conjure-up/openstack: [DEBUG] juju.py:136 - bootstrap cmd: juju bootstrap earl maas/10.1.1.100 --upload-tools --config image-stream=daily --config enable-os-refresh-update=false --config enable-os-upgrade=false --bootstrap-series=xenial --credential earl
Jul  2 11:09:05 maas conjure-up/openstack: [DEBUG] gui.py:54 - Rendering GUI controller for Variant
Jul  2 11:10:14 maas conjure-up/openstack: [DEBUG] gui.py:25 - Chosen spell: openstack-novalxd
Jul  2 11:10:15 maas conjure-up/openstack: [DEBUG] download.py:65 - Extracting spell: bsdtar -xf /tmp/tmpa3rmrp0r/temp.zip -C /home/admin/.cache/conjure-up/openstack-novalxd
Jul  2 11:19:00 maas conjure-up/openstack: [DEBUG] gui.py:29 - handle bootstrap
Jul  2 11:19:00 maas conjure-up/openstack: [ERROR] gui.py:36 - Creating Juju controller "earl" on maas#012Bootstrapping model "controller"#012Starting new instance for initial controller#012Launching instance#012WARNING no architecture was specified, acquiring an arbitrary node#012 - 4y3h7p#012ERROR failed to bootstrap model: bootstrap instance started but did not change to Deployed state: instance "4y3h7p" is started but not deployed
Jul  2 11:19:00 maas conjure-up/openstack: [ERROR] __init__.py:19 - Showing dialog for exception:#012NoneType
Jul  2 11:19:00 maas conjure-up/openstack: [ERROR] __init__.py:19 - Showing dialog for exception:#012Traceback (most recent call last):#012  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run#012    result = self.fn(*self.args, **self.kwargs)#012  File "/usr/share/conjure-up/conjure/juju.py", line 35, in _decorator#012    login()#012  File "/usr/share/conjure-up/conjure/juju.py", line 80, in login#012    raise Exception("Tried to login to a non bootstrapped environment.")#012Exception: Tried to login to a non bootstrapped environment.

Jul  2 11:33:28 maas conjure-up/openstack: [ERROR] Showing dialog for exception:#012Traceback (most recent call last):#012  File "/usr/share/conjure-up/conjure/juju.py", line 385, in do_add_all#012    params=params)#012  File "/usr/share/conjure-up/macumba/v2.py", line 113, in _request#012    'Params': params})#012  File "/usr/share/conjure-up/macumba/v2.py", line 124, in call#012    return self.receive(req_id, timeout)#012  File "/usr/share/conjure-up/macumba/api.py", line 126, in receive#012    raise ServerError(res['Error'], res)#012macumba.errors.ServerError: (ServerError(...), 'application "glance" not found')#012#012During handling of the above exception, another exception occurred:#012#012Traceback (most recent call last):#012  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run#012    result = self.fn(*self.args, **self.kwargs)#012  File "/usr/share/conjure-up/conjure/juju.py", line 36, in _decorator#012    return f(*args, **kwargs)#012  File "/usr/share/conjure-up/conjure/juju.py", line 388, in do_add_all#012    exc_cb(e)#012  File "/usr/share/conjure-up/conjure/controllers/deploy/gui.py", line 25, in __handle_exception#012    app.ui.show_exception_message(exc)#012  File "/usr/share/conjure-up/conjure/ui/__init__.py", line 17, in show_exception_message#012    self.frame.body = ErrorView(ex.args[0])#012  File "/usr/share/conjure-up/ubuntui/views/error.py", line 23, in __init__#012    Padding.center_80(Color.error_major(Text(error))),#012  File "/usr/lib/python3/dist-packages/urwid/widget.py", line 836, in __init__#012    self.set_text(markup)#012  File "/usr/lib/python3/dist-packages/urwid/widget.py", line 879, in set_text#012    self._text, self._attrib = decompose_tagmarkup(markup)#012  File "/usr/lib/python3/dist-packages/urwid/util.py", line 375, in decompose_tagmarkup#012    tl, al = _tagmarkup_recurse(tm, None)#012  File "/usr/lib/python3/dist-packages/urwid/util.py", line 416, in _tagmarkup_recurse#012    raise TagMarkupException("Invalid markup element: %r" % tm)#012urwid.util.TagMarkupException: Invalid markup element: ServerError(ServerError(...), 'application "glance" not found')
Jul  2 11:33:28 maas conjure-up/openstack: [DEBUG] 00_deploy-done:13 - Running deploy-done for OpenStack installation.
Jul  2 11:33:28 maas conjure-up/openstack: [ERROR] error running /home/admin/.cache/conjure-up/openstack-novalxd/conjure/steps/00_deploy-done:#012b'Traceback (most recent call last):\n  File "/home/admin/.cache/conjure-up/openstack-novalxd/conjure/steps/00_deploy-done", line 39, in <module>\n    main()\n  File "/home/admin/.cache/conjure-up/openstack-novalxd/conjure/steps/00_deploy-done", line 14, in main\n    agent_states = juju.agent_states()\nAttributeError: module \'juju\' has no attribute \'agent_states\'\n'
Jul  2 11:33:28 maas conjure-up/openstack: [ERROR] Showing dialog for exception:#012Traceback (most recent call last):#012  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run#012    result = self.fn(*self.args, **self.kwargs)#012  File "/usr/share/conjure-up/conjure/controllers/deploystatus/common.py", line 27, in wait_for_applications#012    raise Exception("Error running {}".format(script))#012Exception: Error running /home/admin/.cache/conjure-up/openstack-novalxd/conjure/steps/00_deploy-done

**Comment by moula** [comment]
I started my deployment 3 times and it's always the same result
Merci. 

Moula.

**Comment by battlemidget** [comment]
hi @moula that error is fixed in the upcoming 2.0.0.4 release due out July 5th. However, I do have it built in ppa:conjure/daily-git if you wish to try that out. You'll need to apt remove conjure-up prior to trying to install from daily-git.

**Comment by battlemidget** [comment]
Fixed in package going out today.

**Comment by moula** [comment]
Hello Adam,

Thank you, i will try to deploy my new bare-metal IAAS  with
MAAS2-JUJU2-OPENSTACK2-CONJURE tomorrow

Merci beaucoup.

Moula de Paris.

2016-07-05 15:05 GMT+02:00 Adam Stokes <notifications@github.com>:
