### ISSUE TITLE
Add information on where to file bugs in exception view

### ISSUE THREAD

**Issue by battlemidget** [ubuntu/conjure-up#203]
Some additional text indicating where people can file bugs at:

```

conjure-up failed, please review logs at /var/log/conjure-up.log
and please submit do a bug at http://launchpad.net/conjure-up
```

**Comment by pmatulis** [comment]
Suggestion:

`conjure-up failed. Review logs at /var/log/conjure-up.log. If appropriate, please submit a bug here: https://github.com/ubuntu/conjure-up/issues/new`

**Comment by battlemidget** [comment]
@pmatulis thanks I like your suggestion
