### ISSUE TITLE
Ungraceful exception

### ISSUE THREAD

**Issue by pmatulis** [ubuntu/conjure-up#214]
From #211 

Was going well, and it's still going ("Deploying application: mysql"), but I got this onscreen:
http://paste.ubuntu.com/18573090/

**Comment by mikemccracken** [comment]
@pmatulis can you paste your current bundle yaml?

**Comment by pmatulis** [comment]
@mikemccracken 

bundle.yaml:
http://paste.ubuntu.com/18574442/

**Comment by battlemidget** [comment]
we should be putting this in bug #211
