### ISSUE TITLE
make deploy_done wait until all services have been allocated

### ISSUE THREAD

**Issue by battlemidget** [ubuntu/conjure-up#238]
It is possible (although very rare) that a deployed application may turn to active state before all of the applications are deployed. This would make the 00_deploy-done script evaluate to true if checking for things like `all(['active'])`.

**Comment by mikemccracken** [comment]
I think this is more of a problem when deploy-done is run before any of the
applications are deployed, since the code then checks this:
```python
if all([state == 'active' for _, state, _ in agent_states])
```
if agent_states is `[]`, that ends up as `all([])`, which evaluates to
`True`.

**Comment by battlemidget** [comment]
Could this fix be as simple as adding the `JUJU_ASYNC_QUEUE` to deploy done?

**Comment by battlemidget** [comment]
https://github.com/ubuntu/conjure-up/commit/f96fe28ccf11d09a187c1f1c1c6e994ebdf0c7ba
