### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 

### ISSUE THREAD

**Issue by gorblimey** [ubuntu/conjure-up#287]
This is the last error before exiting the default conjure-up openstack (4 node bundle).
- maas                 2.0.0~rc2+bzr5156-0ubuntu2~16.04.3
- juju                    2.0-beta13-0ubuntu1~16.04.1
- conjure-up        2.0.0.7-0~201607222212

Jul 24 05:02:43 vista conjure-up/openstack: [ERROR] __init__.py:28 - Showing dialog for exception:#012Traceback (most recent call last):#012  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run#012    result = self.fn(*self.args, **self.kwargs)#012  File "/usr/share/conjure-up/conjure/juju.py", line 35, in _decorator#012    return f(*args, **kwargs)#012  File "/usr/share/conjure-up/conjure/juju.py", line 400, in _deploy_async#012    params={"url": service.csid.as_str()})#012  File "/usr/share/conjure-up/macumba/v2.py", line 118, in _request#012    'Params': params})#012  File "/usr/share/conjure-up/macumba/v2.py", line 127, in call#012    req_id = self.conn.do_send(params)#012  File "/usr/share/conjure-up/macumba/ws.py", line 58, in do_send#012    self.send(json.dumps(json_message))#012  File "/usr/lib/python3/dist-packages/ws4py/websocket.py", line 257, in send#012    message_sender = self.stream.binary_message if binary else self.stream.text_message#012AttributeError: 'NoneType' object has no attribute 'text_message'

**Comment by masaeedu** [comment]
Why was this closed?
