### ISSUE TITLE
conjure-up openstack on 16.04 still not working

### ISSUE THREAD

**Issue by siumafua** [ubuntu/conjure-up#289]
conjure-up openstack
[sudo] password for sysadmin: 
Reading package lists...
Building dependency tree...
Reading state information...
The following packages were automatically installed and are no longer required:
  python-backports.ssl-match-hostname python-jujuclient python-websocket
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  python3-appdirs python3-cinderclient python3-cliff python3-cmd2 python3-debtcollector python3-funcsigs python3-glanceclient python3-json-pointer python3-jsonpatch python3-keyring python3-keystoneauth1 python3-keystoneclient python3-monotonic python3-msgpack
  python3-neutronclient python3-novaclient python3-openstackclient python3-openstacksdk python3-os-client-config python3-oslo.config python3-oslo.i18n python3-oslo.serialization python3-oslo.utils python3-positional python3-requestsexceptions
  python3-secretstorage python3-stevedore python3-unicodecsv python3-warlock python3-wrapt
Suggested packages:
  python-cliff-doc python-debtcollector-doc python-funcsigs-doc python-glanceclient-doc gir1.2-gnomekeyring-1.0 python3-pykde4 python-keystoneauth1-doc python3-requests-kerberos python-openstacksdk-doc python-os-client-config-doc python-positional-doc
  gnome-keyring python-secretstorage-doc
The following NEW packages will be installed:
  openstack python3-appdirs python3-cinderclient python3-cliff python3-cmd2 python3-debtcollector python3-funcsigs python3-glanceclient python3-json-pointer python3-jsonpatch python3-keyring python3-keystoneauth1 python3-keystoneclient python3-monotonic
  python3-msgpack python3-neutronclient python3-novaclient python3-openstackclient python3-openstacksdk python3-os-client-config python3-oslo.config python3-oslo.i18n python3-oslo.serialization python3-oslo.utils python3-positional python3-requestsexceptions
  python3-secretstorage python3-stevedore python3-unicodecsv python3-warlock python3-wrapt
0 upgraded, 31 newly installed, 0 to remove and 0 not upgraded.
Need to get 92.7 kB/1,515 kB of archives.
After this operation, 12.6 MB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 python3-keystoneauth1 all 2.4.1-1ubuntu0.16.04.1 [92.7 kB]
Fetched 92.7 kB in 1s (63.2 kB/s)
Extracting templates from packages: 100%
Selecting previously unselected package python3-cmd2.
(Reading database ... 125601 files and directories currently installed.)
Preparing to unpack .../python3-cmd2_0.6.8-1_all.deb ...
Unpacking python3-cmd2 (0.6.8-1) ...
Selecting previously unselected package python3-wrapt.
Preparing to unpack .../python3-wrapt_1.8.0-5build2_amd64.deb ...
Unpacking python3-wrapt (1.8.0-5build2) ...
Selecting previously unselected package python3-appdirs.
Preparing to unpack .../python3-appdirs_1.4.0-2_all.deb ...
Unpacking python3-appdirs (1.4.0-2) ...
Selecting previously unselected package python3-debtcollector.
Preparing to unpack .../python3-debtcollector_1.3.0-2_all.deb ...
Unpacking python3-debtcollector (1.3.0-2) ...
Selecting previously unselected package python3-keyring.
Preparing to unpack .../python3-keyring_7.3-1ubuntu1_all.deb ...
Unpacking python3-keyring (7.3-1ubuntu1) ...
Selecting previously unselected package python3-positional.
Preparing to unpack .../python3-positional_1.0.1-2_all.deb ...
Unpacking python3-positional (1.0.1-2) ...
Selecting previously unselected package python3-stevedore.
Preparing to unpack .../python3-stevedore_1.12.0-1_all.deb ...
Unpacking python3-stevedore (1.12.0-1) ...
Selecting previously unselected package python3-keystoneauth1.
Preparing to unpack .../python3-keystoneauth1_2.4.1-1ubuntu0.16.04.1_all.deb ...
Unpacking python3-keystoneauth1 (2.4.1-1ubuntu0.16.04.1) ...
Selecting previously unselected package python3-oslo.config.
Preparing to unpack .../python3-oslo.config_1%3a3.9.0-3_all.deb ...
Unpacking python3-oslo.config (1:3.9.0-3) ...
Selecting previously unselected package python3-oslo.i18n.
Preparing to unpack .../python3-oslo.i18n_3.5.0-2_all.deb ...
Unpacking python3-oslo.i18n (3.5.0-2) ...
Selecting previously unselected package python3-msgpack.
Preparing to unpack .../python3-msgpack_0.4.6-1build1_amd64.deb ...
Unpacking python3-msgpack (0.4.6-1build1) ...
Selecting previously unselected package python3-funcsigs.
Preparing to unpack .../python3-funcsigs_0.4-2_all.deb ...
Unpacking python3-funcsigs (0.4-2) ...
Selecting previously unselected package python3-monotonic.
Preparing to unpack .../python3-monotonic_0.6-2_all.deb ...
Unpacking python3-monotonic (0.6-2) ...
Selecting previously unselected package python3-oslo.utils.
Preparing to unpack .../python3-oslo.utils_3.8.0-2_all.deb ...
Unpacking python3-oslo.utils (3.8.0-2) ...
Selecting previously unselected package python3-oslo.serialization.
Preparing to unpack .../python3-oslo.serialization_2.4.0-2_all.deb ...
Unpacking python3-oslo.serialization (2.4.0-2) ...
Selecting previously unselected package python3-keystoneclient.
Preparing to unpack .../python3-keystoneclient_1%3a2.3.1-2_all.deb ...
Unpacking python3-keystoneclient (1:2.3.1-2) ...
Selecting previously unselected package python3-cinderclient.
Preparing to unpack .../python3-cinderclient_1%3a1.6.0-2_all.deb ...
Unpacking python3-cinderclient (1:1.6.0-2) ...
Selecting previously unselected package python3-unicodecsv.
Preparing to unpack .../python3-unicodecsv_0.14.1-1_all.deb ...
Unpacking python3-unicodecsv (0.14.1-1) ...
Selecting previously unselected package python3-cliff.
Preparing to unpack .../python3-cliff_1.15.0-2ubuntu2_all.deb ...
Unpacking python3-cliff (1.15.0-2ubuntu2) ...
Selecting previously unselected package python3-json-pointer.
Preparing to unpack .../python3-json-pointer_1.9-3_all.deb ...
Unpacking python3-json-pointer (1.9-3) ...
Selecting previously unselected package python3-jsonpatch.
Preparing to unpack .../python3-jsonpatch_1.19-3_all.deb ...
Unpacking python3-jsonpatch (1.19-3) ...
Selecting previously unselected package python3-requestsexceptions.
Preparing to unpack .../python3-requestsexceptions_1.1.2-0ubuntu1_all.deb ...
Unpacking python3-requestsexceptions (1.1.2-0ubuntu1) ...
Selecting previously unselected package python3-os-client-config.
Preparing to unpack .../python3-os-client-config_1.16.0-0ubuntu1_all.deb ...
Unpacking python3-os-client-config (1.16.0-0ubuntu1) ...
Selecting previously unselected package python3-neutronclient.
Preparing to unpack .../python3-neutronclient_1%3a4.1.1-2_all.deb ...
Unpacking python3-neutronclient (1:4.1.1-2) ...
Selecting previously unselected package python3-novaclient.
Preparing to unpack .../python3-novaclient_2%3a3.3.1-2_all.deb ...
Unpacking python3-novaclient (2:3.3.1-2) ...
Selecting previously unselected package python3-warlock.
Preparing to unpack .../python3-warlock_1.1.0-1_all.deb ...
Unpacking python3-warlock (1.1.0-1) ...
Selecting previously unselected package python3-glanceclient.
Preparing to unpack .../python3-glanceclient_1%3a2.0.0-2ubuntu0.16.04.1_all.deb ...
Unpacking python3-glanceclient (1:2.0.0-2ubuntu0.16.04.1) ...
Selecting previously unselected package python3-openstacksdk.
Preparing to unpack .../python3-openstacksdk_0.8.1-2_all.deb ...
Unpacking python3-openstacksdk (0.8.1-2) ...
Selecting previously unselected package python3-openstackclient.
Preparing to unpack .../python3-openstackclient_2.3.0-2_all.deb ...
Unpacking python3-openstackclient (2.3.0-2) ...
Selecting previously unselected package python3-secretstorage.
Preparing to unpack .../python3-secretstorage_2.1.3-1_all.deb ...
Unpacking python3-secretstorage (2.1.3-1) ...
Selecting previously unselected package openstack.
Preparing to unpack .../openstack_1.0.7.16.04.1_all.deb ...
Unpacking openstack (1.0.7.16.04.1) ...
Setting up python3-cmd2 (0.6.8-1) ...
Setting up python3-wrapt (1.8.0-5build2) ...
Setting up python3-appdirs (1.4.0-2) ...
Setting up python3-debtcollector (1.3.0-2) ...
Setting up python3-keyring (7.3-1ubuntu1) ...
Setting up python3-positional (1.0.1-2) ...
Setting up python3-stevedore (1.12.0-1) ...
Setting up python3-keystoneauth1 (2.4.1-1ubuntu0.16.04.1) ...
Setting up python3-oslo.config (1:3.9.0-3) ...
update-alternatives: using /usr/bin/python3-oslo-config-generator to provide /usr/bin/oslo-config-generator (oslo-config-generator) in auto mode
Setting up python3-oslo.i18n (3.5.0-2) ...
Setting up python3-msgpack (0.4.6-1build1) ...
Setting up python3-funcsigs (0.4-2) ...
Setting up python3-monotonic (0.6-2) ...
Setting up python3-oslo.utils (3.8.0-2) ...
Setting up python3-oslo.serialization (2.4.0-2) ...
Setting up python3-keystoneclient (1:2.3.1-2) ...
update-alternatives: using /usr/bin/python3-keystone to provide /usr/bin/keystone (keystone) in auto mode
Setting up python3-cinderclient (1:1.6.0-2) ...
update-alternatives: using /usr/bin/python3-cinder to provide /usr/bin/cinder (cinder) in auto mode
Setting up python3-unicodecsv (0.14.1-1) ...
Setting up python3-cliff (1.15.0-2ubuntu2) ...
Setting up python3-json-pointer (1.9-3) ...
update-alternatives: using /usr/bin/python3-jsonpointer to provide /usr/bin/jsonpointer (jsonpointer) in auto mode
Setting up python3-jsonpatch (1.19-3) ...
update-alternatives: using /usr/bin/python3-jsondiff to provide /usr/bin/jsondiff (jsondiff) in auto mode
update-alternatives: using /usr/bin/python3-jsonpatch to provide /usr/bin/jsonpatch (jsonpatch) in auto mode
Setting up python3-requestsexceptions (1.1.2-0ubuntu1) ...
Setting up python3-os-client-config (1.16.0-0ubuntu1) ...
Setting up python3-neutronclient (1:4.1.1-2) ...
update-alternatives: using /usr/bin/python3-neutron to provide /usr/bin/neutron (neutron) in auto mode
Setting up python3-novaclient (2:3.3.1-2) ...
update-alternatives: using /usr/bin/python3-nova to provide /usr/bin/nova (nova) in auto mode
Setting up python3-warlock (1.1.0-1) ...
Setting up python3-glanceclient (1:2.0.0-2ubuntu0.16.04.1) ...
update-alternatives: using /usr/bin/python3-glance to provide /usr/bin/glance (glance) in auto mode
Setting up python3-openstacksdk (0.8.1-2) ...
Setting up python3-openstackclient (2.3.0-2) ...
update-alternatives: using /usr/bin/python3-openstack to provide /usr/bin/openstack (openstack) in auto mode
Setting up python3-secretstorage (2.1.3-1) ...
Setting up openstack (1.0.7.16.04.1) ...
Exception in ev.run():
Traceback (most recent call last):
  File "/usr/share/conjure-up/ubuntui/ev.py", line 83, in run
    cls.loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 1328, in run
    raise self._exc_info[0](self._exc_info[1]).with_traceback(self._exc_info[2])
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/lib/python3/dist-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python3/dist-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python3/dist-packages/urwid/wimp.py", line 643, in keypress
    return self._current_widget.keypress(size, key)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/share/conjure-up/conjure/ui/views/welcome.py", line 35, in keypress
    return super().keypress(size, key)
  File "/usr/lib/python3/dist-packages/urwid/decoration.py", line 836, in keypress
    return self._original_widget.keypress((maxcol,), key)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/lib/python3/dist-packages/urwid/decoration.py", line 621, in keypress
    return self._original_widget.keypress(maxvals, key)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 2269, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/usr/lib/python3/dist-packages/urwid/wimp.py", line 535, in keypress
    self._emit('click')
  File "/usr/lib/python3/dist-packages/urwid/widget.py", line 463, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/usr/lib/python3/dist-packages/urwid/signals.py", line 264, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/lib/python3/dist-packages/urwid/signals.py", line 294, in _call_callback
    return bool(callback(*args_to_pass))
  File "/usr/share/conjure-up/conjure/ui/views/welcome.py", line 72, in done
    self.cb(result.label)
  File "/usr/share/conjure-up/conjure/controllers/welcome.py", line 31, in finish
    self.app.controllers['jujucontroller'].render()
  File "/usr/share/conjure-up/conjure/controllers/jujucontroller.py", line 153, in render
    Juju.switch(c)
  File "/usr/share/conjure-up/conjure/juju.py", line 241, in switch
    cls.login(True)
  File "/usr/share/conjure-up/conjure/juju.py", line 96, in login
    password = account['users'][current_user]['password']
TypeError: list indices must be integers or slices, not NoneType
Traceback (most recent call last):
  File "/usr/bin/conjure-up", line 9, in <module>
    load_entry_point('conjure-up==0.1.2', 'console_scripts', 'conjure-up')()
  File "/usr/share/conjure-up/conjure/app.py", line 222, in main
    app.start()
  File "/usr/share/conjure-up/conjure/app.py", line 171, in start
    EventLoop.run()
  File "/usr/share/conjure-up/ubuntui/ev.py", line 83, in run
    cls.loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 1328, in run
    raise self._exc_info[0](self._exc_info[1]).with_traceback(self._exc_info[2])
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/lib/python3/dist-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python3/dist-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python3/dist-packages/urwid/wimp.py", line 643, in keypress
    return self._current_widget.keypress(size, key)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/share/conjure-up/conjure/ui/views/welcome.py", line 35, in keypress
    return super().keypress(size, key)
  File "/usr/lib/python3/dist-packages/urwid/decoration.py", line 836, in keypress
    return self._original_widget.keypress((maxcol,), key)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/lib/python3/dist-packages/urwid/decoration.py", line 621, in keypress
    return self._original_widget.keypress(maxvals, key)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 2269, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/usr/lib/python3/dist-packages/urwid/wimp.py", line 535, in keypress
    self._emit('click')
  File "/usr/lib/python3/dist-packages/urwid/widget.py", line 463, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/usr/lib/python3/dist-packages/urwid/signals.py", line 264, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/lib/python3/dist-packages/urwid/signals.py", line 294, in _call_callback
    return bool(callback(*args_to_pass))
  File "/usr/share/conjure-up/conjure/ui/views/welcome.py", line 72, in done
    self.cb(result.label)
  File "/usr/share/conjure-up/conjure/controllers/welcome.py", line 31, in finish
    self.app.controllers['jujucontroller'].render()
  File "/usr/share/conjure-up/conjure/controllers/jujucontroller.py", line 153, in render
    Juju.switch(c)
  File "/usr/share/conjure-up/conjure/juju.py", line 241, in switch
    cls.login(True)
  File "/usr/share/conjure-up/conjure/juju.py", line 96, in login
    password = account['users'][current_user]['password']
TypeError: list indices must be integers or slices, not NoneType
sysadmin@cloud:~$ juju version
2.0-beta13-xenial-amd64

**Comment by battlemidget** [comment]
This is due to us following beta releases of Juju. You need to install the pre-releases now until we get to a spot where a new version can be uploaded to the archive.

See http://conjure-up.io for information on installing the prerelease, essentially:

```
$ sudo apt-add-repository ppa:conjure-up/next
$ sudo apt-add-repository ppa:juju/devel
$ sudo apt update
$ sudo apt install conjure-up
$ conjure-up openstack
```
