### ISSUE TITLE
crash when choosing 'lxd' cloud

### ISSUE THREAD

**Issue by mikemccracken** [ubuntu/conjure-up#35]
It's not in the Schema in providers.py

looking at newcloud/gui.py, It looks like I should've picked 'localhost' ? 

do we need to filter out 'lxd' somehow, or does it need to get added?

**Comment by mikemccracken** [comment]
I just tried again and I can't pick 'localhost' so I don't understand why newcloud/gui.py checks if this.cloud=='localhost'

**Comment by battlemidget** [comment]
So between beta6 and beta7 of juju it changed from lxd to localhost, however the actual type has stayed 'lxd'. I'll look at this some more tomorrow but it's probably just unfinished work from the switch between betas

**Comment by mikemccracken** [comment]
Oh, I was using beta 6. I will upgrade and try again. Thanks.

**Comment by battlemidget** [comment]
I dont think this applies any longer

**Comment by mikemccracken** [comment]
:+1:
