### ISSUE TITLE
conjure-up openstack landscape deploy failure

### ISSUE THREAD

**Issue by stephen-kainos** [ubuntu/conjure-up#43]
I'm getting the following stacktrace when trying to deploy openstack using conjure-up on 16.04. I've replicated this on multiple environments both physical and virtual nodes. 

![image](https://cloud.githubusercontent.com/assets/8288896/15630584/dbd6b718-2539-11e6-8f03-6c548662daf3.png)

Using MAAS Version 2.0.0 (beta3+bzr4941), getting the same issue with beta 5.

**Comment by battlemidget** [comment]
Thanks we're still working on getting maas 2.0 tested. Juju just started supporting it in beta 7

**Comment by moula** [comment]
I try to deploy with maas 2.0 and without success. 
MAAS Version 2.0.0 (beta5+bzr5026)
conjure-up is already the newest version (2.0.0-0~369~ubuntu16.04.1)
moula@maas:~$ conjure-up openstack
[warning] Could not find spell in charmstore.

thank's.

**Comment by battlemidget** [comment]
This will be fixed in next monday's release
