### ISSUE TITLE
Openstack LXD Single installation failing

### ISSUE THREAD

**Issue by kapde** [ubuntu/conjure-up#8]
Hi,

When trying an OpenStack LXD single install on 16.04 it fails fatally on a pair of steps:

- The first is easy to solve as it is only a missing id_rsa.pub in the .ssh home dir
- The second, where I am stuck, complains about: No keypair with a name or ID of 'ubuntu-keypair' exists

I'm just starting so I have limited troubleshooting skills but any help to find at least a workaround will be greatly appreciated.

Best regards,

Kapde

**Comment by battlemidget** [comment]
Can you add the ppa? Ive fixed most of those issues related to ssh

```
apt-add-repository ppa:conjure/ppa
apt update
apt upgrade
```

**Comment by kapde** [comment]
I tried to complete the conjure after adding the PPA but it got stuck
somewhat, so I reinstalled my ubuntu server from scratch and restarted the
conjure. Now I'm getting another error (see attached)

Regards,

Pau

2016-04-26 14:10 GMT+02:00 Adam Stokes <notifications@github.com>:

**Comment by battlemidget** [comment]
Hi kapde,

I don't think attachments work through email can you add it to the issue itself?

**Comment by battlemidget** [comment]
Also you can run:

```
# hit enter without typing any passwords in
$ ssh-keygen 
$ source /usr/share/openstack/bundles/common-openstack/novarc
$ openstack keypair create --public-key $HOME/.ssh/id_rsa.pub ubuntu-keypair
```

This should get a keypair added without having to redeploy. You can also import keypairs through the openstack dashboard.

**Comment by kapde** [comment]
Sorry, it was displaying something like:

Oops there was a problem with your install:

Reason: Creating Juju controller "local.janessa" on lxd/localhostBostrapping model "admin"Starting new instance for initial controllerLaunching instance starting instance can't get info for image 'ubuntu-xenial': not found

Regards

**Comment by battlemidget** [comment]
Ah interesting, can you make sure you're using juju 2.0 beta 6? there were fixes for that in there

**Comment by rhickstedjr** [comment]
This works great only issue is after I deploy on my laptop and reboot 1/2 of the containers start.

Tried 4-5x times.

root@rhicksted-XPS-15-9550:/home/rhicksted# lxc list
+------------------------------------------------------+---------+----------------------+------+------------+-----------+
|                         NAME                         |  STATE  |         IPV4         | IPV6 |    TYPE    | SNAPSHOTS |
+------------------------------------------------------+---------+----------------------+------+------------+-----------+
| juju-23f522df-89ab-4fc4-84de-0390ef44f13f-machine-0  | RUNNING | 10.20.158.16 (eth0)  |      | PERSISTENT | 0         |
+------------------------------------------------------+---------+----------------------+------+------------+-----------+
| juju-8131e5ee-a4fc-4ad9-8890-f5fb311e10bc-machine-0  | RUNNING | 10.20.158.19 (eth0)  |      | PERSISTENT | 0         |
+------------------------------------------------------+---------+----------------------+------+------------+-----------+
| juju-8131e5ee-a4fc-4ad9-8890-f5fb311e10bc-machine-1  | RUNNING | 10.20.158.112 (eth0) |      | PERSISTENT | 0         |
+------------------------------------------------------+---------+----------------------+------+------------+-----------+
| juju-8131e5ee-a4fc-4ad9-8890-f5fb311e10bc-machine-10 | RUNNING | 10.20.158.2 (eth0)   |      | PERSISTENT | 0         |
+------------------------------------------------------+---------+----------------------+------+------------+-----------+
| juju-8131e5ee-a4fc-4ad9-8890-f5fb311e10bc-machine-11 | RUNNING | 10.20.158.198 (eth0) |      | PERSISTENT | 0         |
+------------------------------------------------------+---------+----------------------+------+------------+-----------+
| juju-8131e5ee-a4fc-4ad9-8890-f5fb311e10bc-machine-12 | RUNNING | 10.20.158.86 (eth0)  |      | PERSISTENT | 0         |
+------------------------------------------------------+---------+----------------------+------+------------+-----------+
| juju-8131e5ee-a4fc-4ad9-8890-f5fb311e10bc-machine-13 | RUNNING | 10.20.158.99 (eth0)  |      | PERSISTENT | 0         |
+------------------------------------------------------+---------+----------------------+------+------------+-----------+
| juju-8131e5ee-a4fc-4ad9-8890-f5fb311e10bc-machine-14 | RUNNING | 10.20.158.106 (eth0) |      | PERSISTENT | 0         |
+------------------------------------------------------+---------+----------------------+------+------------+-----------+
| juju-8131e5ee-a4fc-4ad9-8890-f5fb311e10bc-machine-15 | RUNNING | 10.20.158.136 (eth0) |      | PERSISTENT | 0         |
+------------------------------------------------------+---------+----------------------+------+------------+-----------+
| juju-8131e5ee-a4fc-4ad9-8890-f5fb311e10bc-machine-16 | RUNNING | 10.20.158.208 (eth0) |      | PERSISTENT | 0         |
+------------------------------------------------------+---------+----------------------+------+------------+-----------+
| juju-8131e5ee-a4fc-4ad9-8890-f5fb311e10bc-machine-2  | ERROR   |                      |      | PERSISTENT | 0         |
+------------------------------------------------------+---------+----------------------+------+------------+-----------+
| juju-8131e5ee-a4fc-4ad9-8890-f5fb311e10bc-machine-3  | STOPPED |                      |      | PERSISTENT | 0         |
+------------------------------------------------------+---------+----------------------+------+------------+-----------+
| juju-8131e5ee-a4fc-4ad9-8890-f5fb311e10bc-machine-4  | STOPPED |                      |      | PERSISTENT | 0         |
+------------------------------------------------------+---------+----------------------+------+------------+-----------+
| juju-8131e5ee-a4fc-4ad9-8890-f5fb311e10bc-machine-5  | STOPPED |                      |      | PERSISTENT | 0         |
+------------------------------------------------------+---------+----------------------+------+------------+-----------+
| juju-8131e5ee-a4fc-4ad9-8890-f5fb311e10bc-machine-6  | STOPPED |                      |      | PERSISTENT | 0         |
+------------------------------------------------------+---------+----------------------+------+------------+-----------+
| juju-8131e5ee-a4fc-4ad9-8890-f5fb311e10bc-machine-7  | STOPPED |                      |      | PERSISTENT | 0         |
+------------------------------------------------------+---------+----------------------+------+------------+-----------+
| juju-8131e5ee-a4fc-4ad9-8890-f5fb311e10bc-machine-8  | STOPPED |                      |      | PERSISTENT | 0         |
+------------------------------------------------------+---------+----------------------+------+------------+-----------+
| juju-8131e5ee-a4fc-4ad9-8890-f5fb311e10bc-machine-9  | STOPPED |                      |      | PERSISTENT | 0         |
+------------------------------------------------------+---------+----------------------+------+------------+-----------+

Regards

**Comment by battlemidget** [comment]
@rhickstedjr, interesting, can you attach /var/log/lxd/<container-name>/lxc.log of the ones that aren't started?

So for example, the last entry in the above output would be:

`/var/log/lxd/ juju-8131e5ee-a4fc-4ad9-8890-f5fb311e10bc-machine-9 /lxc.log`

Thanks

**Comment by rhickstedjr** [comment]
2-9 in order.


Thanks,

Rick

________________________________

**Comment by battlemidget** [comment]
Unfortunately I dont think it works by attaching to the email, can you attach directly to the bug?

**Comment by rhickstedjr** [comment]
Here they are via the web page.

[Archive.zip](https://github.com/Ubuntu-Solutions-Engineering/conjure-up/files/248104/Archive.zip)

Thanks,

Rick

**Comment by battlemidget** [comment]
Thanks I'll talk with the lxd guys tomorrow

**Comment by checoman** [comment]
Same here except all servers stay in "Allocating" for more than a day and never changed, started over from a fresh installation and do the same. Is an HP PC lab and no ZFS used.

**Comment by secroft** [comment]
If you're using zfs as a backing store for those containers, there's a possibility that the zfs module didn't load on reboot, so a modprobe of zfs should fix the issue. There's another bug not on github that's been filed for this issue.

**Comment by rhickstedjr** [comment]
I am using ZFS in the example above, but I also noticed the issue without ZFS deployment as well.

If the module was not loading on reboots why would 1/2 the containers start?

**Comment by battlemidget** [comment]
> If the module was not loading on reboots why would 1/2 the containers start?

Yea we're asking that too, I am still working with LXD guys on possible reasons why this is happening.

**Comment by rhickstedjr** [comment]
Any luck?  Can we put a delay between container starts?

Thanks,

Rick

**Comment by battlemidget** [comment]
Still debugging, there seems to be a race between juju connecting to the lxd endpoint. Because it is difficult to reproduce we'll need more time.

**Comment by battlemidget** [comment]
@rhickstedjr, digging through this with LXD guys now, hopefully will have an update soon.

**Comment by rhickstedjr** [comment]
Good deal!  I would really like to test more of the solution.

Thanks,

Rick

**Comment by battlemidget** [comment]
@rhickstedjr, I've opened a bug with LXD over at https://github.com/lxc/lxd/issues/2001 feel free to subscribe and if possible provide any additional information they may need

**Comment by rhickstedjr** [comment]
No work around to stagger the container start time on reboot to affect the possible race?

Thanks,

Rick

**Comment by battlemidget** [comment]
Not that I know of unfortunately

**Comment by rhickstedjr** [comment]
This works:

https://bitsandslices.wordpress.com/2015/08/26/autostarting-lxd-containers/


boot.autostart.delay	lxc.start.delay

stagger based on the container #

ex 16 has a higher delay than 15..14..13..etc.

Thanks,

Rick

**Comment by battlemidget** [comment]
So that worked for you? If so this is great information I can pass along to the right people

**Comment by rhickstedjr** [comment]
Yes, tried 5x reboots.

Thanks,

Sent from my iPhone

On May 7, 2016, at 12:00 PM, Adam Stokes <notifications@github.com<mailto:notifications@github.com>> wrote:


So that worked for you? If so this is great information I can pass along to the right people

-

**Comment by battlemidget** [comment]
Perfect thanks

**Comment by battlemidget** [comment]
@rhickstedjr I built a new openstack package in the ppa, could you retry your tests without the delay options and let me know if you still run into issues?

**Comment by jpmitchell** [comment]
I am unable to make this work as well. The installation gets as far as deploying the services and then hangs on Keystone. The installation fails after a while. The only LXD container deployed is MAAS. I see this in the /var/log/openstack.log file:

john@openstack-dev:~$ tail /var/log/openstack.log 
May 25 09:44:50 openstack-dev openstack: [WARNING]
May 25 09:44:50 openstack-dev openstack: [ERROR] There was an error during the post processing phase, retrying.
May 25 09:44:56 openstack-dev openstack: [WARNING]
May 25 09:44:56 openstack-dev openstack: [ERROR] There was an error during the post processing phase, retrying.
May 25 09:49:23 openstack-dev openstack: [WARNING] pollinate binary not found
May 25 09:49:26 openstack-dev openstack: message repeated 2 times: [ [WARNING] pollinate binary not found]
May 25 09:52:09 openstack-dev openstack: [WARNING] pollinate binary not found
May 25 09:55:23 openstack-dev openstack: message repeated 7 times: [ [WARNING] pollinate binary not found]
May 25 09:57:46 openstack-dev openstack: [WARNING] pollinate binary not found
May 25 09:57:48 openstack-dev openstack: [WARNING] pollinate binary not found

After some googling for the pollinate error, I ran across an issue with MAAS 2.0 and juju 2.0. So is this currently broken and just does not work? Thanks for the help.

References:
https://github.com/ubuntu/conjure-up/issues/9
https://bugs.launchpad.net/juju-core/+bug/1564577

**Comment by battlemidget** [comment]
Yea MAAS 2.0 doesn't quite work with our stuff yet see #38 to track it's progress. I will be working on getting that going this week and into next

**Comment by jpmitchell** [comment]
Thank you for the reply. Is it possible to work around this and still use conjure-up to do the install? I am guessing not.

**Comment by battlemidget** [comment]
@jpmitchell Other than use MAAS 1.9 i dont think there is a way around it for now. Our next release is due May 30th so I'll try to have this fix in there by then.

**Comment by jpmitchell** [comment]
@battlemidget Sounds good. Thanks again for the quick update!

**Comment by jpmitchell** [comment]
Any update on the release? Thanks!

**Comment by battlemidget** [comment]
Running behind hope to do a release soon

**Comment by jpmitchell** [comment]
Sounds good. Thanks again for the update. Hope it goes well.

**Comment by battlemidget** [comment]
@jpmitchell We're hoping to do a release today but it won't have full maas 2.0 support yet. I've set that to be done by the release next Monday June 13th. I'll keep you posted on it's progress

**Comment by SaMnCo** [comment]
LXD Openstack failing as well. I can't pass "pre processing checks" (right after the commit). I'm on a fresh 16.04, with the ppa, picking everything vanilla. 
Machine is a Intel NUC with core i7, 16GB RAM, extremely classic. 

Let me know if there are any logs or stuff I should put here. 

Thx,

**Comment by battlemidget** [comment]
Still waiting on the openstack package to reach xenial-updates, can you upgrade to the openstack package in proposed and see if it still persists @SaMnCo

**Comment by rhickstedjr** [comment]
I would get a system with 32G RAM.  I had real issues at 16.

Note:  the NUC can go to 32G, but the cost is 300$ for a set of DIMMs,  which is almost the cost of the I7 NUC.

Thanks,

Sent from my iPhone

On Jun 7, 2016, at 4:14 AM, Samuel Cozannet <notifications@github.com<mailto:notifications@github.com>> wrote:


LXD Openstack failing as well. I can't pass "pre processing checks" (right after the commit). I'm on a fresh 16.04, with the ppa, picking everything vanilla.
Machine is a Intel NUC with core i7, 16GB RAM, extremely classic.

Let me know if there are any logs or stuff I should put here.

Thx,

-

**Comment by battlemidget** [comment]
Packages pushed to xenial-updates should resolve the initial poster's bug.

**Comment by battlemidget** [comment]
@jpmitchell please track #38 for maas 2.0 support, ive got the initial code done just doing some testing so it can be included in next monday's release.

**Comment by jpmitchell** [comment]
Thanks. I am already following it.

**Comment by luisrosal** [comment]
Hello,

Having a similar problem. Trying to perform single machine installation and having an error.

administrator@openstack:~$ tail /var/log/openstack.log
Aug  8 16:10:57 openstack openstack: [WARNING] pollinate binary not found
Aug  8 16:11:10 openstack openstack: message repeated 2 times: [ [WARNING] pollinate binary not found]
Aug  8 16:12:31 openstack openstack: [WARNING] pollinate binary not found
Aug  8 16:12:33 openstack openstack: message repeated 2 times: [ [WARNING] pollinate binary not found]
Aug  8 16:17:11 openstack openstack: [WARNING] pollinate binary not found


From the output of the installation script

Setting up python3-glanceclient (1:2.0.0-2ubuntu0.16.04.1) ...
update-alternatives: using /usr/bin/python3-glance to provide /usr/bin/glance (glance) in auto mode
Setting up python3-openstackclient (2.3.0-2) ...
update-alternatives: using /usr/bin/python3-openstack to provide /usr/bin/openstack (openstack) in auto mode
Setting up openstack (1.0.7.16.04.1) ...
Processing triggers for libc-bin (2.23-0ubuntu3) ...
Job for lxd-containers.service failed because the control process exited with error code. See "systemctl status lxd-containers.service" and "journalctl -xe" for details.
lxd-containers.service couldn't start.
Job for lxd-containers.service failed because the control process exited with error code. See "systemctl status lxd-containers.service" and "journalctl -xe" for details.
lxd-containers.service couldn't restart.
Exception in ev.run():
Traceback (most recent call last):
  File "/usr/share/conjure-up/ubuntui/ev.py", line 83, in run
    cls.loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 1326, in run
    self._loop.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 345, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1276, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.5/selectors.py", line 441, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/bin/conjure-up", line 9, in <module>
    load_entry_point('conjure-up==0.1.2', 'console_scripts', 'conjure-up')()
  File "/usr/share/conjure-up/conjure/app.py", line 222, in main
    app.start()
  File "/usr/share/conjure-up/conjure/app.py", line 171, in start
    EventLoop.run()
  File "/usr/share/conjure-up/ubuntui/ev.py", line 83, in run
    cls.loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 1326, in run
    self._loop.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 345, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1276, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.5/selectors.py", line 441, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
KeyboardInterrupt

Not sure if I'm doing anything wrong or it's the script which is not ok.

Thanks

**Comment by battlemidget** [comment]
Looks like your LXD isn't configured properly

**Comment by luisrosal** [comment]
Thanks. I found the problem was the /var/lib/lxd/containers path wasn't created. Once I've created previous to launch the installation, I don't have this error. Once I've resolved that I'm getting a new error and I have no clue about what can be the problem:

Setting up python3-oslo.config (1:3.9.0-3) ...
update-alternatives: using /usr/bin/python3-oslo-config-generator to provide /usr/bin/oslo-config-generator (oslo-config-generator) in auto mode
Setting up python3-keystoneclient (1:2.3.1-2) ...
update-alternatives: using /usr/bin/python3-keystone to provide /usr/bin/keystone (keystone) in auto mode
Setting up python3-cinderclient (1:1.6.0-2) ...
update-alternatives: using /usr/bin/python3-cinder to provide /usr/bin/cinder (cinder) in auto mode
Setting up python3-glanceclient (1:2.0.0-2ubuntu0.16.04.1) ...
update-alternatives: using /usr/bin/python3-glance to provide /usr/bin/glance (glance) in auto mode
Setting up python3-openstackclient (2.3.0-2) ...
update-alternatives: using /usr/bin/python3-openstack to provide /usr/bin/openstack (openstack) in auto mode
Setting up openstack (1.0.7.16.04.1) ...
Processing triggers for libc-bin (2.23-0ubuntu3) ...
Exception in ev.run():
Traceback (most recent call last):
  File "/usr/share/conjure-up/ubuntui/ev.py", line 83, in run
    cls.loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 1326, in run
    self._loop.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 331, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1262, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.5/selectors.py", line 441, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/bin/conjure-up", line 9, in <module>
    load_entry_point('conjure-up==0.1.2', 'console_scripts', 'conjure-up')()
  File "/usr/share/conjure-up/conjure/app.py", line 222, in main
    app.start()
  File "/usr/share/conjure-up/conjure/app.py", line 171, in start
    EventLoop.run()
  File "/usr/share/conjure-up/ubuntui/ev.py", line 83, in run
    cls.loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 1326, in run
    self._loop.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 331, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1262, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.5/selectors.py", line 441, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
KeyboardInterrupt

administrator@openstack:~$ tail /var/log/openstack.log
Aug  9 10:04:22 openstack openstack: [WARNING] pollinate binary not found
Aug  9 10:04:26 openstack openstack: message repeated 2 times: [ [WARNING] pollinate binary not found]
Aug  9 10:04:56 openstack openstack: [WARNING] pollinate binary not found
Aug  9 10:04:59 openstack openstack: message repeated 2 times: [ [WARNING] pollinate binary not found]
Aug  9 10:08:33 openstack openstack: [WARNING] pollinate binary not found

Thanks for the help.

Luis

**Comment by sivaramaprasad** [comment]
Hi,

When trying an OpenStack LXD single install on 16.04  it is giving all machine states as error.

here i pasted my $ sudo juju status

MODEL    CONTROLLER  CLOUD/REGION   VERSION
default  localhost   lxd/localhost  2.0-beta15

APP                    VERSION  STATUS   EXPOSED  ORIGIN      CHARM                  REV  OS
ceph                            unknown  false    jujucharms  ceph                   4    ubuntu
ceph-radosgw                    unknown  false    jujucharms  ceph-radosgw           5    ubuntu
cinder                          unknown  false    jujucharms  cinder                 3    ubuntu
cinder-ceph                              false    jujucharms  cinder-ceph            2    ubuntu
glance                          unknown  false    jujucharms  glance                 2    ubuntu
keystone                        unknown  false    jujucharms  keystone               2    ubuntu
mysql                           unknown  false    jujucharms  percona-cluster        2    ubuntu
neutron-api                     unknown  false    jujucharms  neutron-api            3    ubuntu
neutron-gateway                 unknown  false    jujucharms  neutron-gateway        3    ubuntu
neutron-openvswitch                      false    jujucharms  neutron-openvswitch    3    ubuntu
nova-cloud-controller           unknown  false    jujucharms  nova-cloud-controller  4    ubuntu
nova-compute                    unknown  false    jujucharms  nova-compute           3    ubuntu
openstack-dashboard             unknown  false    jujucharms  openstack-dashboard    2    ubuntu
rabbitmq-server                 unknown  false    jujucharms  rabbitmq-server        5    ubuntu

RELATION                 PROVIDES               CONSUMES               TYPE
mon                      ceph                   ceph                   peer
mon                      ceph                   ceph-radosgw           regular
ceph                     ceph                   cinder-ceph            regular
ceph                     ceph                   glance                 regular
ceph                     ceph                   nova-compute           regular
cluster                  ceph-radosgw           ceph-radosgw           peer
identity-service         ceph-radosgw           keystone               regular
cluster                  cinder                 cinder                 peer
storage-backend          cinder                 cinder-ceph            subordinate
image-service            cinder                 glance                 regular
identity-service         cinder                 keystone               regular
shared-db                cinder                 mysql                  regular
cinder-volume-service    cinder                 nova-cloud-controller  regular
amqp                     cinder                 rabbitmq-server        regular
cluster                  glance                 glance                 peer
identity-service         glance                 keystone               regular
shared-db                glance                 mysql                  regular
image-service            glance                 nova-cloud-controller  regular
image-service            glance                 nova-compute           regular
amqp                     glance                 rabbitmq-server        regular
cluster                  keystone               keystone               peer
shared-db                keystone               mysql                  regular
identity-service         keystone               neutron-api            regular
identity-service         keystone               nova-cloud-controller  regular
identity-service         keystone               openstack-dashboard    regular
cluster                  mysql                  mysql                  peer
shared-db                mysql                  neutron-api            regular
shared-db                mysql                  nova-cloud-controller  regular
cluster                  neutron-api            neutron-api            peer
neutron-plugin-api       neutron-api            neutron-gateway        regular
neutron-plugin-api       neutron-api            neutron-openvswitch    regular
neutron-api              neutron-api            nova-cloud-controller  regular
amqp                     neutron-api            rabbitmq-server        regular
cluster                  neutron-gateway        neutron-gateway        peer
quantum-network-service  neutron-gateway        nova-cloud-controller  regular
amqp                     neutron-gateway        rabbitmq-server        regular
neutron-plugin           neutron-openvswitch    nova-compute           regular
amqp                     neutron-openvswitch    rabbitmq-server        regular
cluster                  nova-cloud-controller  nova-cloud-controller  peer
cloud-compute            nova-cloud-controller  nova-compute           regular
amqp                     nova-cloud-controller  rabbitmq-server        regular
neutron-plugin           nova-compute           neutron-openvswitch    subordinate
compute-peer             nova-compute           nova-compute           peer
amqp                     nova-compute           rabbitmq-server        regular
cluster                  openstack-dashboard    openstack-dashboard    peer
cluster                  rabbitmq-server        rabbitmq-server        peer

UNIT                     WORKLOAD  AGENT       MACHINE  PUBLIC-ADDRESS  PORTS  MESSAGE
ceph-radosgw/0           unknown   allocating  3                               Waiting for agent initialization to finish
ceph/0                   unknown   allocating  0                               Waiting for agent initialization to finish
ceph/1                   unknown   allocating  1                               Waiting for agent initialization to finish
ceph/2                   unknown   allocating  2                               Waiting for agent initialization to finish
cinder/0                 unknown   allocating  4                               Waiting for agent initialization to finish
glance/0                 unknown   allocating  5                               Waiting for agent initialization to finish
keystone/0               unknown   allocating  6                               Waiting for agent initialization to finish
mysql/0                  unknown   allocating  7                               Waiting for agent initialization to finish
neutron-api/0            unknown   allocating  8                               Waiting for agent initialization to finish
neutron-gateway/0        unknown   allocating  9                               Waiting for agent initialization to finish
nova-cloud-controller/0  unknown   allocating  10                              Waiting for agent initialization to finish
nova-compute/0           unknown   allocating  11                              Waiting for agent initialization to finish
openstack-dashboard/0    unknown   allocating  12                              Waiting for agent initialization to finish
rabbitmq-server/0        unknown   allocating  13                              Waiting for agent initialization to finish

MACHINE  STATE  DNS  INS-ID   SERIES  AZ
0        error       pending  xenial  
1        error       pending  xenial  
2        error       pending  xenial  
3        error       pending  xenial  
4        error       pending  xenial  
5        error       pending  xenial  
6        error       pending  xenial  
7        error       pending  xenial  
8        error       pending  xenial  
9        error       pending  xenial  
10       error       pending  xenial  
11       error       pending  xenial  
12       error       pending  xenial  
13       error       pending  xenial  

Thanks in Advance
Sureshbabu J

**Comment by battlemidget** [comment]
Your containers aren't starting up for some reason.

**Comment by sivaramaprasad** [comment]
how can i get rid this error

**Comment by JohnAdamsy** [comment]
Hi all, new entrant here. 

When juju starts the bootstrapping process, this errors halts the process: 
`"error: flag provided but not defined: --upload-tools" `

I'm trying to get it set up on a bare metal server running  Ubuntu 16.04.

**Comment by battlemidget** [comment]
You'll need to get a newer conjure-up, see http://conjure-up.io for install details

**Comment by JohnAdamsy** [comment]
@battlemidget Thanks much 😄 . That did the trick. The error is gone. Let me resume this and I will report back.  👍

**Comment by JohnAdamsy** [comment]
Reporting back to duty. Things have been smooth on my side so far, but I can't seem to get the home run yet 😅 

It's failing randomly while at a it. 

`juju show-status` 

Just picked from the long list:

```
glance/0*                   error     idle        7        10.239.127.135            hook failed: "install"

neutron-gateway/0*        error     idle        11       10.239.127.51               hook failed: "install"
```

**Comment by battlemidget** [comment]
Can you do:

```
juju ssh glance/0
```

Then inside the container run:

```
pastebinit /var/log/juju/unit-glance-0.log
```

And provide that link in this bug

**Comment by JohnAdamsy** [comment]
I just did, got in via ssh, but I'm not sure if it's my network at the moment. Getting this:

`Failed to contact the server: [Errno socket error] The write operation timed out`

on running `pastebinit /var/log/juju/unit-glance-0.log`

**Comment by battlemidget** [comment]
Are you behind a firewall or anything? This could be another indication as to why the installation is failing (problematic network)

**Comment by JohnAdamsy** [comment]
I think you're right. The server is in a location with a mighty country wide government firewall.

**Comment by JohnAdamsy** [comment]
@battlemidget I moved countries and I was able to restart the process on a stable network. Here's an output from an lxd container that's has failed: http://paste.ubuntu.com/23614089/

**Comment by Laguna-x** [comment]
@battlemidget the first:
same issue
"error: flag provided but not defined: --upload-tools"

I'm trying to get it set up on a bare metal server running Ubuntu 16.04.1 (installed as maas region, next added rack localy on the same server, next installed openstack, next installed conjure)

installed conjure as written at "http://conjure-up.io"

$ uname -a
Linux mSys 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

what kind of info can i provide?

and next - it's to difficult to type all api key in dialog - why paste do not work like in bash console (working over putty (ssh) from windows pc)?

**Comment by battlemidget** [comment]
> and next - it's to difficult to type all api key in dialog - why paste do not work like in bash console (working over putty (ssh) from windows pc)?

I think you can do SHIFT+INSERT and it'll paste in putty

Did you run

`sudo snap install conjure-up --classic`?

**Comment by Laguna-x** [comment]
@battlemidget , yes
`snap install conjure-up --classic`
wrote that installed latest version. tried twice. every selection in menu (single/nova-LXD/MaaS) shows the same message. will try another once later today, but i think it will be the same

PS forgot about keyboard )) windows makes me stupid )) 10x

**Comment by battlemidget** [comment]
Make sure you apt-get remove juju-2.0 as the snap provides that already
